### PR TITLE
Fix dyes

### PR DESCRIPTION
**Pull request by richardhendricks**
This fix will stop TecTech from modifying the GregTech Dyes enum, and update to the latest version of GT5U.

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
I imagine Tec actually does this for a reason. (His machines are blue)

Ps, why can I review things?

**Comment by richardhendricks** [comment]
If he wants machine-metal tinted machines, we can add a new tint for him.

**Comment by draknyte1** [comment]
Don't know if you read the code, but he adjusts blue colours. Nothing to do with machine metal.

**Comment by Dream-Master** [comment]
@richardhendricks the gt build be must be changed too or build will fail.

**Comment by richardhendricks** [comment]
Are you asking or telling?  I don't know if it will or not, but it seems like it should be kept in step with whatever we release.

**Comment by Technus** [comment]
Just as i mentioned earlier, by default GT machine metal is not perfect white. The only reason that I am aware of why @richardhendricks  wants that is so textures look white even tho greg explicitly made them tinted to avoid visual confusion. This white machine metal would avoid color distorsion on colorful casing templates... Iirc his other reasonimg is that "no one uses paint".

My code above just tries to more evenly space this 3 dyes for increased contrast. While his chamges target to make machine metal to be white.

**Comment by richardhendricks** [comment]
With defaults (machine metal is a blue tint) machines colors are not consistent.

Removing machine metal tint makes the colors consistent.


I am not sure how the tinting avoids "visual confusion."  With what?

**Comment by Technus** [comment]
Other way is to apply machine metal to block actually used in machines like the

https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/gthandler/casings/GT_Block_CasingsNH.java#L162

gtnh pyrolyze casing

**Comment by richardhendricks** [comment]
I am not sure what you mean by evenly spacing the dyes, they aren't any different than the defaults

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Dyes.java

https://github.com/Technus/TecTech/pull/11/commits/39542d672a0cafc492aa168d903167e3b00925ea

**Pull request merged**
